apiVersion: ovn.openstack.org/v1beta1
kind: OVNController
metadata:
  name: ovncontroller-sample
spec:
  ovsContainerImage: "quay.io/podified-antelope-centos9/openstack-ovn-base:current-podified"
  ovnContainerImage: "quay.io/podified-antelope-centos9/openstack-ovn-controller:current-podified"
  external-ids:
    system-id: "random"
    ovn-bridge: "br-int"
    ovn-encap-type: "geneve"
